---
abstract: 'DBIC Query Log and Query Analyzer '
author:
  - 'John Napiorkowski, C<< <jjnapiork@cpan.org> >>'
build_requires:
  Data::Dump: 0
  ExtUtils::MakeMaker: 6.42
  HTTP::Request::Common: 0
  Plack::Builder: 0
  Plack::Middleware::DBIC::QueryLog: 0
  Plack::Test: 0
  Scalar::Util: 0
  Test::Fatal: 0
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.02'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Plack::Middleware::Debug::DBIC::QueryLog
name: Plack-Middleware-Debug-DBIC-QueryLog
no_index:
  directory:
    - example
    - inc
    - t
requires:
  DBIx::Class::QueryLog: 0
  DBIx::Class::QueryLog::Analyzer: 0
  Moo: 0.009005
  Plack: 0
  Plack::Middleware::DBIC::QueryLog: 0.05
  Plack::Middleware::Debug: 0
  SQL::Abstract: 1.70
  perl: 5.8.8
resources:
  homepage: http://search.cpan.org/dist/Plack-Middleware-Debug-DBIC-QueryLog/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/jjn1056/Plack-Middleware-Debug-DBIC-QueryLog.git
version: 0.07
